### ISSUE TITLE
VS Code file open issue

### ISSUE THREAD

**Issue by imranbarbhuiya** [snyk/vscode-extension#114]
VS Code the extension isn't working properly.

When I first installed it, it was working properly but few days now it's no longer working as expected. I restarted, uninstalled and installed the extension but still it's not working.

Here are the issues

- it's not showing error's line by line in my editor
![image](https://user-images.githubusercontent.com/74945038/145928143-2b54d0e8-5d91-4c78-8cd3-d1eb118bf469.png)

No error in that line, but only showing in problem tab.

- from problem tab if I click on a problem, it's not opening that file
![image](https://user-images.githubusercontent.com/74945038/145928189-c63dbaf4-9164-4bef-8854-63e112c73b7d.png)

I don't know if it's happening only with me else you can just install the extension, and you'll be able to reproduce

**Comment by michelkaporin** [comment]
Could you perhaps provide some reproduction steps?
Does this happen with the following repo: https://github.com/snyk-labs/nodejs-goof as well for you?

**Comment by imranbarbhuiya** [comment]
I'll test this out when I'll get time. But one think I noticed is this issue occurs only in vscode workspaces and if I use a folder then the extension works fine.

**Comment by imranbarbhuiya** [comment]
I've tested with some more projects and I can confirm that the issue occurs only in workspaces, and it's working fine in folders.
