### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by imranbarbhuiya** [snyk/vscode-extension#115]
Sometimes Snyk shows some warnings, but we want to ignore it. In order to ignore it, we need to go to every file and ignore the warning with a comment. It'll be good if we can ignore it for the entire project, like using a Snyk config file.

**Comment by michelkaporin** [comment]
Would `.snyk` file work in your case, @imranbarbhuiya ?
https://docs.snyk.io/snyk-cli/test-for-vulnerabilities/the-.snyk-file

**Comment by imranbarbhuiya** [comment]
I don't think so. I was looking for a config file to disables some code style rules for entire workspaces. Like I don't like the warning on return statements inside of a `forEach` loop where I'm using return to stop executing rest of the codes but snyks warns that return won't be able to return anything from a foreach loop. Ik it's a valid warning but I still wants to disable it.

**Comment by michelkaporin** [comment]
@imranbarbhuiya Got it, thanks. Please submit a ticket via our official support channel here https://support.snyk.io/hc/en-us. This is related to Snyk Code product and first has to be done on the product level before we can provide functionality in the VS Code extension.
