### ISSUE TITLE
[Question] - Connect VS Code with Snyk stuck

### ISSUE THREAD

**Issue by bondezbond** [snyk/vscode-extension#116]
👋🏾  Sorry if this isn't the right place to ask a questions. I'm trying to use the snyk vscode extension. 

1. When I open the snyc tab it gives me two green tabs to connect to snyk. 
2. I click on the link which opens the browser to authenticate. 
3. Browser says `Your account has been authenticated. Snyk is now ready to be used.` 
4. But when I got back to vscode it just keeps loading
![image](https://user-images.githubusercontent.com/4400773/146251992-38cf33f3-ad8c-4180-9630-b96f6f3d74be.png)

**Comment by michelkaporin** [comment]
@bondezbond You can mitigate this by entering Snyk token directly into extension settings in VS Code.

To resolve this, we would probably need to know little more about your network configuration. Are you using proxy or VPN?

**Comment by bondezbond** [comment]
Thanks for that. I can confirm that worked.

1. I am not using a VPN
2. I can confirm that I am getting assigned an IPv6 address from my isp

**Comment by michelkaporin** [comment]
Hi @bondezbond 👋 We have fixed the underlying cause and released it today. Could you please verify if the authentication works for you now?

**Comment by michelkaporin** [comment]
@bondezbond great, thanks for reporting it!
