### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by imranbarbhuiya** [snyk/vscode-extension#121]
![image](https://user-images.githubusercontent.com/74945038/147442519-8560f828-56ee-4f01-9797-b2b0ec0b7c85.png)

Here I'm importing a function with name getUser and defining one locally with the same name(inside an object) but snyk thinks it's the same function and showing warnings.

![image](https://user-images.githubusercontent.com/74945038/147442660-59603d81-8472-4167-bf20-67d073184da0.png)

**Comment by imranbarbhuiya** [comment]
Also, I disabled `Code Quality` scan, but I'm still seeing these warnings.

![image](https://user-images.githubusercontent.com/74945038/147480917-16ce0858-d880-42f1-99b1-d16c0d8dce91.png)

I restarted VSC, deleted dccache, but it's still showing.

**Comment by michelkaporin** [comment]
This should be fixed since #192.
