### ISSUE TITLE
Scan Failed

### ISSUE THREAD

**Issue by payneBrandon** [snyk/vscode-extension#128]
When attempting to test a .NET solution with --file=.sln I run into "Scan failed" with the attached error. Note that I am authenticated and can successfully run `snyk test --file=.sln` from the command line.

![image](https://user-images.githubusercontent.com/2932159/148620661-6b6fef93-05f1-4520-b8b4-b411a069f2d8.png)

**Comment by michelkaporin** [comment]
@payneBrandon Hi, you can provide the full path to your solution file as a temporary workaround.

**Comment by payneBrandon** [comment]
Thanks for the response! This does work as a temporary workaround, and I'm able to get a scan to run properly.

**Comment by michelkaporin** [comment]
@payneBrandon the fix has landed into the latest version to make it work with relative file path ✅.

**Comment by payneBrandon** [comment]
> @payneBrandon the fix has landed into the latest version to make it work with relative file path ✅.

Tested and up and running. Thanks for the help!
