### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by olad32** [snyk/vscode-extension#132]
The extension auth process correctly launches the browser page to Authenticate, but when the last page says "Your account has been authenticated. Snyk is now ready to be used." and i go back to vscode, the extension remains in the same state (unautenticated), the Snyk extension progress bar keeps loading forever. 

https://test-ipv6.com/ says that i have no ipv6 assigned

Here is the output of the vscode extension : 
> [Info] Starting full scan
> [Info] Snyk CLI version is up-to-date.
> [Info] Starting full scan
> [Info] Starting full scan
> [Info] IPv6 is used to authenticate.

Extension version : 1.2.6

I have not tried to manually enter the token in vscode config as i don't know where to find this token.

Thx

**Comment by michelkaporin** [comment]
@olad32 Are you behind any proxy?

You can find the token under your account settings on https://app.snyk.io/account to manually enter it.

**Comment by olad32** [comment]
no proxy, it works with the manually entered token, thanks

**Comment by michelkaporin** [comment]
@olad32 this should be hopefully resolved by now in the extension version >=1.2.7. Would you be kind to try again and tell us  if it works for you now?
