### ISSUE TITLE
Disabling Code Quality doesn't disable warnings

### ISSUE THREAD

**Issue by glics** [snyk/vscode-extension#138]
When you disable `snyk.features.codeQuality` the "Code Quality" tree view in the sidebar says "Snyk Code Quality is disabled", as expected, but the "Problems" panel keeps showing Snyk Code Quality warnings:

![Screenshot_20220118_181824](https://user-images.githubusercontent.com/5410803/149988561-d3e9c3f1-df47-4c2f-aef7-3a1f566e50ef.png)

**Comment by michelkaporin** [comment]
Fixes in #192
