### ISSUE TITLE
Camel case detection for css property detecting values

### ISSUE THREAD

**Issue by GGProgrammation** [snyk/vscode-extension#141]
In my case, I have a transition property style with a value of 'background-color' to define what to change.
Since 'background-color' is also a css property, Snyk detects that it should be camel cased. 

Since it's the value I don't think it should be detected.
![image](https://user-images.githubusercontent.com/31279534/151225144-4235e4b6-9499-45c0-8e52-153d889b6872.png)

Also the ignore doesn't work and the error is still shown.
![image](https://user-images.githubusercontent.com/31279534/151225460-c3a21671-6e9f-4f6c-acdd-cdaa33f3dd27.png)

Thank you

**Comment by michelkaporin** [comment]
Hi @GGProgrammation! We're currently working on false positive reporting functionality within our extension. Once it's out you'll be able to submit such issues via UI in VS Code.

Meanwhile, you can use our official [contact form](https://snyk.io/contact-us/?utm_source=vsc) to report it. Feel free to link this issue there.
