### ISSUE TITLE
isNaN warning doesn't go away when I use Number.isNaN

### ISSUE THREAD

**Issue by prionkor** [snyk/vscode-extension#143]
Version used: 1.2.7

**Comment by michelkaporin** [comment]
Hi @prionkor. Does the issue https://github.com/snyk/vscode-extension/issues/121 describe the problem you're having or is it a different one? Please provide the repro steps, if not.

**Comment by prionkor** [comment]
I have looked into it again today. The warning seems to be gone. So I changed from `Number.isNaN()` to `isNaN()` which suppose to trigger the warning and after saving the warning is not picking up. 

My guess is the extension is a bit slow to pick up these warnings? Any settings I can tweak?

**Comment by michelkaporin** [comment]
@prionkor Can you share a small reproducible example together with the steps you did? A GIF/video would be much appreciated as well.

**Comment by prionkor** [comment]
Looks like There is no warning in `isNaN()` now. I will reopen this if I can reproduce the issue.
