### ISSUE TITLE
Reports incorrect number of arguments in function

### ISSUE THREAD

**Issue by selfagency** [snyk/vscode-extension#164]
Not sure the parsing engine's working so well. It doesn't recognize the correct number of arguments in a function.

![CleanShot 2022-03-08 at 10 58 13](https://user-images.githubusercontent.com/2541728/157276009-06a9f030-9c47-4fbd-bf2d-9e996e526457.png)

**Comment by michelkaporin** [comment]
@selfagency are you sure this comes from Snyk Code scanning? This seems to be a compiler warning, rather a security issue.

**Comment by selfagency** [comment]
I am positive it was Snyk and not TypeScript that was returning that error but maybe VS Code was choking

**Comment by michelkaporin** [comment]
@selfagency please reach out to our Snyk Code product support via [web](http://support.snyk.io) or email at support@snyk.io to submit false positive, if you are confident it's Snyk Code Quality warning that was shown to you. It has nothing to do with the extension codebase unfortunately.
