### ISSUE TITLE
VSCode marketplace listing images broken

### ISSUE THREAD

**Issue by emchap** [snyk/vscode-extension#239]
Didn't see anyone having flagged this before, so just wanted to call it out in case it wasn't known! 

On https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner, looks like a big portion of the image markdown is malformed and so not rendering:

![image](https://user-images.githubusercontent.com/9934079/176748668-2d309044-a07f-46b3-b443-6f2c790e253b.png)

![image](https://user-images.githubusercontent.com/9934079/176748701-b935e0ae-bea1-4341-8e25-20baca80fa35.png)

![image](https://user-images.githubusercontent.com/9934079/176748745-a67de8fe-be30-47b4-b7e5-3445d41e5f06.png)

**Comment by michelkaporin** [comment]
Thanks, this has been addressed in #238 and will be fixed in the next version.
