### ISSUE TITLE
VSCode extension hangs at "Waiting 0%"

### ISSUE THREAD

**Issue by vertiman** [snyk/vscode-extension#47]
The plugin was working the past few days, but when I started VSCode today (running in remote/SSH) it loads config, "collects files" for a few seconds, and then sits at "Waiting 0%" forever.

I'm not sure where/what logs to look at to see if there's a root cause.  We're on a paid Snyk code account.

Thanks!

**Comment by michelkaporin** [comment]
@vertiman does it happen on all type of projects or just with a particular one? Does the problem still persist for you?

**Comment by vertiman** [comment]
@michelkaporin it happened for a few days, and seems to have self-resolved.  It does seem much slower now that it's resolved though?

**Comment by JohnBatts418** [comment]
Hi @vertiman 
We found we had a spike in analysis duration during the window you commented but its now resolved and you should be back to seeing normal times. Can you please confirm. Thanks!

**Comment by JohnBatts418** [comment]
Closing this issue as no reponse received. If you see this issue arise again, please say here. Thankyou!
